In [18]:
import pandas as pd
import seaborn as sns

In [19]:
df = pd.read_csv('/Users/luwei/Desktop/MMAI/data sicence /kc_house_data.csv')

In [20]:
df.info()
#No missing data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   id             21613 non-null  int64  
 1   date           21613 non-null  object 
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64  
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64  
 6   sqft_lot       21613 non-null  int64  
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64  
 9   view           21613 non-null  int64  
 10  condition      21613 non-null  int64  
 11  grade          21613 non-null  int64  
 12  sqft_above     21613 non-null  int64  
 13  sqft_basement  21613 non-null  int64  
 14  yr_built       21613 non-null  int64  
 15  yr_renovated   21613 non-null  int64  
 16  zipcode        21613 non-null  int64  
 17  lat            21613 non-null  float64
 18  long  

In [21]:
df.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [22]:
pip install scikit-learn  

Note: you may need to restart the kernel to use updated packages.


In [23]:
#feature engineering 
import numpy as np

In [24]:
df['waterfront'].unique()

array([0, 1])

In [25]:
df['view'].unique()

array([0, 3, 4, 2, 1])

In [26]:
df['condition'].unique()

array([3, 5, 4, 1, 2])

In [27]:
#Transform date into a datetime data format 

In [28]:
df['date'] = pd.to_datetime(df['date'])
df['year'] = df['date'].dt.year

In [15]:
df

id       date     price  bedrooms  bathrooms  sqft_living  \
0      7129300520 2014-10-13  221900.0         3       1.00         1180   
1      6414100192 2014-12-09  538000.0         3       2.25         2570   
2      5631500400 2015-02-25  180000.0         2       1.00          770   
3      2487200875 2014-12-09  604000.0         4       3.00         1960   
4      1954400510 2015-02-18  510000.0         3       2.00         1680   
...           ...        ...       ...       ...        ...          ...   
21608   263000018 2014-05-21  360000.0         3       2.50         1530   
21609  6600060120 2015-02-23  400000.0         4       2.50         2310   
21610  1523300141 2014-06-23  402101.0         2       0.75         1020   
21611   291310100 2015-01-16  400000.0         3       2.50         1600   
21612  1523300157 2014-10-15  325000.0         2       0.75         1020   

       sqft_lot  floors  waterfront  view  ...  sqft_above  sqft_basement  \
0          5650     1.0           0     0  ...        1180              0   
1          7242     2.0           0     0  ...        2170            400   
2         10000     1.0           0     0  ...         770              0   
3          5000     1.0           0     0  ...        1050            910   
4          8080     1.0           0     0  ...        1680              0   
...         ...     ...         ...   ...  ...         ...            ...   
21608      1131     3.0           0     0  ...        1530              0   
21609      5813     2.0           0     0  ...        2310              0   
21610      1350     2.0           0     0  ...        1020              0   
21611      2388     2.0           0     0  ...        1600              0   
21612      1076     2.0           0     0  ...        1020              0   

       yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0          1955             0    98178  47.5112 -122.257           1340   
1          1951          1991    98125  47.7210 -122.319           1690   
2          1933             0    98028  47.7379 -122.233           2720   
3          1965             0    98136  47.5208 -122.393           1360   
4          1987             0    98074  47.6168 -122.045           1800   
...         ...           ...      ...      ...      ...            ...   
21608      2009             0    98103  47.6993 -122.346           1530   
21609      2014             0    98146  47.5107 -122.362           1830   
21610      2009             0    98144  47.5944 -122.299           1020   
21611      2004             0    98027  47.5345 -122.069           1410   
21612      2008             0    98144  47.5941 -122.299           1020   

       sqft_lot15  year  
0            5650  2014  
1            7639  2014  
2            8062  2015  
3            5000  2014  
4            7503  2015  
...           ...   ...  
21608        1509  2014  
21609        7200  2015  
21610        2007  2014  
21611        1287  2015  
21612        1357  2014  

[21613 rows x 22 columns]

In [29]:
df['month'] = df['date'].dt.month

In [30]:
df['day'] = df['date'].dt.day

In [31]:
df

id       date     price  bedrooms  bathrooms  sqft_living  \
0      7129300520 2014-10-13  221900.0         3       1.00         1180   
1      6414100192 2014-12-09  538000.0         3       2.25         2570   
2      5631500400 2015-02-25  180000.0         2       1.00          770   
3      2487200875 2014-12-09  604000.0         4       3.00         1960   
4      1954400510 2015-02-18  510000.0         3       2.00         1680   
...           ...        ...       ...       ...        ...          ...   
21608   263000018 2014-05-21  360000.0         3       2.50         1530   
21609  6600060120 2015-02-23  400000.0         4       2.50         2310   
21610  1523300141 2014-06-23  402101.0         2       0.75         1020   
21611   291310100 2015-01-16  400000.0         3       2.50         1600   
21612  1523300157 2014-10-15  325000.0         2       0.75         1020   

       sqft_lot  floors  waterfront  view  ...  yr_built  yr_renovated  \
0          5650     1.0           0     0  ...      1955             0   
1          7242     2.0           0     0  ...      1951          1991   
2         10000     1.0           0     0  ...      1933             0   
3          5000     1.0           0     0  ...      1965             0   
4          8080     1.0           0     0  ...      1987             0   
...         ...     ...         ...   ...  ...       ...           ...   
21608      1131     3.0           0     0  ...      2009             0   
21609      5813     2.0           0     0  ...      2014             0   
21610      1350     2.0           0     0  ...      2009             0   
21611      2388     2.0           0     0  ...      2004             0   
21612      1076     2.0           0     0  ...      2008             0   

       zipcode      lat     long  sqft_living15  sqft_lot15  year  month  day  
0        98178  47.5112 -122.257           1340        5650  2014     10   13  
1        98125  47.7210 -122.319           1690        7639  2014     12    9  
2        98028  47.7379 -122.233           2720        8062  2015      2   25  
3        98136  47.5208 -122.393           1360        5000  2014     12    9  
4        98074  47.6168 -122.045           1800        7503  2015      2   18  
...        ...      ...      ...            ...         ...   ...    ...  ...  
21608    98103  47.6993 -122.346           1530        1509  2014      5   21  
21609    98146  47.5107 -122.362           1830        7200  2015      2   23  
21610    98144  47.5944 -122.299           1020        2007  2014      6   23  
21611    98027  47.5345 -122.069           1410        1287  2015      1   16  
21612    98144  47.5941 -122.299           1020        1357  2014     10   15  

[21613 rows x 24 columns]